"""initial

Revision ID: 14abbc35689b
Revises: 87893e429d1f
Create Date: 2025-09-19 18:31:06.553289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14abbc35689b'
down_revision: Union[str, Sequence[str], None] = '87893e429d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_pickup_details', 'store_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_pickup_details', 'store_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
