"""create all tables

Revision ID: 3d1a8d3da8fb
Revises: 5f6053a7702c
Create Date: 2025-08-01 14:00:13.777279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d1a8d3da8fb'
down_revision: Union[str, Sequence[str], None] = '5f6053a7702c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('class_name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('order_delivery_details',
    sa.Column('order_delivery_detail_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('order_delivery_detail_id')
    )
    op.create_table('order_types',
    sa.Column('order_type_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('order_type_id')
    )
    op.create_table('refresh_token_bl',
    sa.Column('refresh_token_bl_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('refresh_token_bl_id'),
    sa.UniqueConstraint('jti')
    )
    op.create_table('stores',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=56), nullable=False),
    sa.Column('opening_hours', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_table('order_pickup_details',
    sa.Column('order_pickup_detail_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_pickup_detail_id')
    )
    op.create_index(op.f('ix_order_pickup_details_store_id'), 'order_pickup_details', ['store_id'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('specification', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('months_warranty', sa.Integer(), nullable=True),
    sa.Column('country_origin', sa.String(length=128), nullable=False),
    sa.Column('sale_percent', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index('idx_specification_gin', 'products', ['specification'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('home_address', sa.String(), nullable=True),
    sa.Column('pickup_store_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('user', 'seller', 'admin', name='user_role_enum'), nullable=False),
    sa.ForeignKeyConstraint(['pickup_store_id'], ['stores.store_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('baskets',
    sa.Column('basket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('basket_id')
    )
    op.create_index(op.f('ix_baskets_product_id'), 'baskets', ['product_id'], unique=False)
    op.create_index(op.f('ix_baskets_user_id'), 'baskets', ['user_id'], unique=False)
    op.create_table('favorite_products',
    sa.Column('favorite_product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('favorite_product_id')
    )
    op.create_index(op.f('ix_favorite_products_product_id'), 'favorite_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_favorite_products_user_id'), 'favorite_products', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('new', 'confirmed', 'preparing', 'delivered', 'ready', 'finished', 'cancelled', name='order_status_enum'), nullable=False),
    sa.Column('order_type_id', sa.Integer(), nullable=True),
    sa.Column('order_detail_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_type_id'], ['order_types.order_type_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('months_used', sa.Integer(), nullable=True),
    sa.Column('positive', sa.String(length=512), nullable=True),
    sa.Column('negative', sa.String(length=512), nullable=True),
    sa.Column('comment', sa.String(length=1024), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_reviews_product_id'), 'reviews', ['product_id'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_table('stores_quantity_info',
    sa.Column('stores_quantity_info_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stores_quantity_info_id')
    )
    op.create_index(op.f('ix_stores_quantity_info_product_id'), 'stores_quantity_info', ['product_id'], unique=False)
    op.create_index(op.f('ix_stores_quantity_info_store_id'), 'stores_quantity_info', ['store_id'], unique=False)
    op.create_table('purchases',
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('purchase_id')
    )
    op.create_index(op.f('ix_purchases_order_id'), 'purchases', ['order_id'], unique=False)
    op.create_index(op.f('ix_purchases_product_id'), 'purchases', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchases_product_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_order_id'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_stores_quantity_info_store_id'), table_name='stores_quantity_info')
    op.drop_index(op.f('ix_stores_quantity_info_product_id'), table_name='stores_quantity_info')
    op.drop_table('stores_quantity_info')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_product_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('orders')
    op.drop_index(op.f('ix_favorite_products_user_id'), table_name='favorite_products')
    op.drop_index(op.f('ix_favorite_products_product_id'), table_name='favorite_products')
    op.drop_table('favorite_products')
    op.drop_index(op.f('ix_baskets_user_id'), table_name='baskets')
    op.drop_index(op.f('ix_baskets_product_id'), table_name='baskets')
    op.drop_table('baskets')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index('idx_specification_gin', table_name='products', postgresql_using='gin')
    op.drop_table('products')
    op.drop_index(op.f('ix_order_pickup_details_store_id'), table_name='order_pickup_details')
    op.drop_table('order_pickup_details')
    op.drop_table('stores')
    op.drop_table('refresh_token_bl')
    op.drop_table('order_types')
    op.drop_table('order_delivery_details')
    op.drop_table('categories')
    # ### end Alembic commands ###
