"""initial

Revision ID: 41218fa42e31
Revises: 9b2db4b87e65
Create Date: 2025-09-21 22:55:16.147974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41218fa42e31'
down_revision: Union[str, Sequence[str], None] = '9b2db4b87e65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_text_user',
    sa.Column('history_text_user_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query_text', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['query_text'], ['products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_text_user_id')
    )
    op.create_index(op.f('ix_history_text_user_query_text'), 'history_text_user', ['query_text'], unique=False)
    op.create_index(op.f('ix_history_text_user_user_id'), 'history_text_user', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_text_user_user_id'), table_name='history_text_user')
    op.drop_index(op.f('ix_history_text_user_query_text'), table_name='history_text_user')
    op.drop_table('history_text_user')
    # ### end Alembic commands ###
