"""v2 sqlalchemy

Revision ID: 5a25af585c43
Revises: 44bc7eb9bfa6
Create Date: 2025-10-03 20:53:51.002514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a25af585c43'
down_revision: Union[str, Sequence[str], None] = '44bc7eb9bfa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('history_text_user', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('history_text_user', 'query_text',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('history_text_user', 'query_text',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('history_text_user', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
