"""inital

Revision ID: 9b2db4b87e65
Revises: 14abbc35689b
Create Date: 2025-09-19 18:37:53.926694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b2db4b87e65'
down_revision: Union[str, Sequence[str], None] = '14abbc35689b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('purchases_product_id_fkey'), 'purchases', type_='foreignkey')
    op.create_foreign_key(None, 'purchases', 'products', ['product_id'], ['product_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.create_foreign_key(op.f('purchases_product_id_fkey'), 'purchases', 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
