"""edit nullable

Revision ID: a7f44b310d59
Revises: 5a25af585c43
Create Date: 2025-10-04 13:48:51.218925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f44b310d59'
down_revision: Union[str, Sequence[str], None] = '5a25af585c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('baskets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('baskets', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('categories', 'title',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('favorite_products', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('favorite_products', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_delivery_details', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_pickup_details', 'store_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_pickup_details', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_types', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('orders', 'order_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'order_detail_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'title',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('products', 'months_warranty',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('purchases', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('purchases', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'months_used',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'positive',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('reviews', 'negative',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('reviews', 'is_edited',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('stores_quantity_info', 'store_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stores_quantity_info', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stores_quantity_info', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stores_quantity_info', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stores_quantity_info', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stores_quantity_info', 'store_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'is_edited',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('reviews', 'negative',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('reviews', 'positive',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('reviews', 'months_used',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('purchases', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('purchases', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'months_warranty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'title',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('orders', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'order_detail_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'order_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_types', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('order_pickup_details', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_pickup_details', 'store_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_delivery_details', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('favorite_products', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('favorite_products', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('categories', 'title',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('baskets', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('baskets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
