"""initial

Revision ID: b093034e0e77
Revises: 9dd60b15cfa7
Create Date: 2025-09-06 19:10:23.821721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b093034e0e77'
down_revision: Union[str, Sequence[str], None] = '9dd60b15cfa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
