"""initial

Revision ID: b892b4e56942
Revises: b093034e0e77
Create Date: 2025-09-19 18:24:37.110124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b892b4e56942'
down_revision: Union[str, Sequence[str], None] = 'b093034e0e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_delivery_details', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_order_delivery_details_user_id'), 'order_delivery_details', ['user_id'], unique=False)
    op.create_foreign_key(None, 'order_delivery_details', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.add_column('order_pickup_details', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_order_pickup_details_user_id'), 'order_pickup_details', ['user_id'], unique=False)
    op.create_foreign_key(None, 'order_pickup_details', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_pickup_details', type_='foreignkey')
    op.drop_index(op.f('ix_order_pickup_details_user_id'), table_name='order_pickup_details')
    op.drop_column('order_pickup_details', 'user_id')
    op.drop_constraint(None, 'order_delivery_details', type_='foreignkey')
    op.drop_index(op.f('ix_order_delivery_details_user_id'), table_name='order_delivery_details')
    op.drop_column('order_delivery_details', 'user_id')
    # ### end Alembic commands ###
