"""initial

Revision ID: f6b38ba836c0
Revises: 61536950cdf9
Create Date: 2025-09-06 17:57:55.803528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6b38ba836c0'
down_revision: Union[str, Sequence[str], None] = '61536950cdf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_baskets_product_id'), table_name='baskets')
    op.drop_column('baskets', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baskets', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_baskets_product_id'), 'baskets', ['product_id'], unique=False)
    # ### end Alembic commands ###
